os: osx
osx_image: xcode10
language: swift
script:
  - xcodebuild clean build test -project CI/CI.xcodeproj -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.0,name=iPhone 6s" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO